### ISSUE TITLE
Log folder created in installation folder

### ISSUE THREAD

**Issue by bgyori** [ndexbio/ndex2-client#26]
The code here: https://github.com/ndexbio/ndex2-client/blob/master/ndex2/__init__.py#L19-L23
attempts to make a `logs` directory within the package folder. This doesn't work if the package is installed in a folder (e.g. with sudo pip install) for which the user doesn't normally have write permission. This led me to a situation where I can't import the package due to the folder creation erroring. Is there some way to change this behavior?

**Comment by bgyori** [comment]
Looks like there is a relevant commit (https://github.com/ndexbio/ndex2-client/commit/7a0e6717b438aae4a0f4de4fe885b0cee51ab6b8) which might solve this, my error was with the version on PyPI which  hasn't been released since.

**Comment by coleslaw481** [comment]
Pushed a release candidate [2.0.1rc4](https://pypi.org/project/ndex2/2.0.1rc4/) to PyPI. After a bit more testing will do a formal release.

**Comment by coleslaw481** [comment]
2.0.1 has been released with fix to [PyPI](https://pypi.org/project/ndex2/). Closing ticket, please reopen if there is still an issue. 

I noticed there is an [ndex2-dev](https://pypi.org/project/ndex2-dev/) and [ndex2-performance](https://pypi.org/project/ndex2/) repo that are almost identical to the ndex2 repo. Going to probably deprecate these repos since they are confusing. If a release of this fix to those repos is needed please let me know.
